# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e67c139c97b1e381f20a80da292df98d292bb42dea0fd63f9fc171e0d9fb2ecc5f48045d797c6ae51a04524cc50ceb50d6a5b3791163561211e959706e2baafc

test:
  secret_key_base: e9204ebd16c82a130db6c8e39c7ca4f3f1c3f91897d147acd9bc5c90eb2ff5105ee88c71ee7c34917bf73faf6c588b0bbb53bd6df1c96d06d78b7987cb31f882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
